// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsxhubruzqqvbmewapgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeGh1YnJ1enFxdmJtZXdhcGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjI4MDgsImV4cCI6MjA2NjQzODgwOH0.rJjNEKwvpo-AQyx1rOVO-LIK_T5OWOwlM09t0N15zfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);